// JavaScript Document
// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'>01.¿Podemos decidir hoy la fecha de embarque?<br>02.¿Cuándo podéis embarcar la mercancía como antes?<br>03.Me gustaría saber si podéis embarcar la mercancía en septiembre.<br>04.¿Cuánto tiempo necesitan transportar en barco desde aquí hasta Canadá?<br>05.¿Hay posibilidades de anticipar el embarque para el mes de marzo?<br>06.El embarque debe efectuarse antes del 20 de junio.<br>07.Queremos aplazar el embarque para el 12 de agosto.<br>08.Espero anticipar el embarque de la primera partida de mercancías para el final de junio.<br>09.Es demasiado tarde embarcar las mercancías en octubre. Perderemos la buena venta. A ver si tienen otros remedios.<br>10.Las mercancías tienen que llegar antes de marzo. Si no, no podemos alcanzar el período de la venta.<br>11.Si no pueden despachar las mercancías antes del próximo miércoles, nos vemos obligados a cancelar el pedido.<br>12.Les agradeceré si inmediatamente despachan las mercancías que hemos pedido.<br>13.Necesitamos urgentemente este pedido. Haga el favor de efectuar el envío lo antes posible.<br>14.¿Puede despacharnos 100 toneladas de mercancías primeramente, para satisfacer nuestra necesidad urgente?<br>15.Hagan el favor de asegurar el embarque del barco de “La Paz” que partirá alrededor del día 15 de octubre.<br>16.¿Cuánto se puede embarcar como antes?<br>17.Podemos embarcar la mercancía dentro de tres meses, una vez que recibamos tu carta de crédito.<br>18.¿Generalmente cuánto tiempo necesitáis para entregar la mercancía?<br>19.En general podemos entregar la mercancía dentro de tres meses después de recibir la carta de crédito concerniente.<br>20.Espero que podáis embarcar a la vista de la carta de crédito de nuestra parte.<br></font>";
}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Vamos a hablar de la fecha del embarque. ¿Puede embarcar en marzo? <br/>B: Creo que no. A: ¿Entonces cuándo se puede embarcar como antes?<br/>B: Hasta abril.<br/>A: Es demasiado tarde. Sabes, en nuestro mercado, se vende mucho en mayo, y también tardamos dos semanas en hacer los trámites aduaneros. ¿Se puedeembarcar en marzo?<br/>B: Está bien, tomamos una especial consideración a su petición. Podemos entregar la mitad en marzo, y el resto, en abril.<br/>A: Vale. Está bien.<br/><br/><b>Diálogo 2</b><br/>A: ¿A continuación podemos hablar de la fecha del embarque?<br/>B: Está bien. Podemos embarcar la mercancía dentro de los tres meses desde que recibamos su carta de crédito.<br/>A: Tres meses es demasiado largo. Y nuestros otros vendedores pueden embarcar al recibir la carta de crédito dentro de un mes.<br/>B: Pero sabe que hay la petición especial en este pedido, tenemos que elaborarlo según la petición.<br/>A: Entiendo. Pero también tenemos que alcanzar el mejor tiempo de venta. Entonces, ¿se puede embarcar dentro de dos meses?<br/>B: Lo intentaremos.<br/>A: Muchas gracias por su colaboración.<br/><br/><br/><b>Diálogo 3</b><br/>A: ¿Les envío las muestras por avión?<br/>B: Sí, envíenoslas lo más pronto posible, para que confirmemos el pedido.<br/>A: Bueno, el transporte aéreo es el más rápido.<br/>B: Entonces, para los productos del pedido, ¿prefieren utilizar el transporte ferroviario o marítimo?<br/>A: El transporte marítimo.<br/>B: ¿Cuántos días se tarda de Tianjin a Barcelona?<br/>A: Más de un mes.</font>";	
	}
	
	
