// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'>01.&nbsp;&nbsp;¿Pdría enviarme un catálogo de nuestras y una lista de precios?<br>02. Si la oferta es aceptable, es posible que les hagamos un pedido de gran cantidad.<br>03. Denos los precios más favorables, y dígannos la cantidad mínima para hacer un pedido.<br>04. Sírvanse hacernos la oferta más favorable, para llegar a un acuerdo.<br>05. Quisiera conocer la cantidad mínima para hacer un pedido de cada medida y cada color.<br>06.Estamos deseosos de conocer sus ofertas de<br>07. Estamos deseosos de conocer sus ofertas de televisor.<br>08. He aquí la lista de precios, deseo que nos coticen el precio CIF Barcelona.<br>09. Aquí tiene usted nuestra lista de pedido, quisiera que nos ofreciera los precios más favorables, CIF Vancouver.<br>10.Deseo que me ofrezca los precios más bajos, CIF Vancouver.<br>11.Necesitamos el precio CIF Jakarta y sírvanse una oferta de las mercancías de la carta adjunta de solicitud de informes.<br>12.Dennos los precios de los productos de la lista adjunta. Necesitamos el precio CIF Valencia.<br>13.Quiséramos conocer los precios más bajos de los siguientes productos de su empresa.<br>14.Si pueden hacernos una oferta de este producto, nos sentiremos muy alegres.<br>15.Cotícennos el precio CIF Hong Kong de guantes de cuero hachos a mano.<br>16.Queremos saber las ofertas de este sombrero.<br>17.¿Podría dar el precio del artículo número tres?<br>18.Díganos la cotización del producto número 6 de grupo 100 del catálogo.<br>19.Dennos el precio real de la mercancía Número 303 con cantidad de 5000 piezas FOB Singapur.<br>20.Cotícennos el precio FOB Veracruz de cien toneladas de cacahuete.</font>";
}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Buenas taedes. Soy Juan, comerciante mexicano. Tenga mi tarjeta.<br/>B: Buenas taedes. Señor. ¿En qué puedo servirle?<br/>A: Nos interesamos mucho por los productos de la ferretería de su empresa. ¿Nos podría dar una oferta?<br/>B: Bueno, éste es el último catálogo de nuestra empresa que abarca precios de cada producto.<br/>A: Muchas gracias. Lo voy a leer atendamente.</font><br/><font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><br/><b>Diálogo 2</b><br/>A: Pensamos pedir unas lámparas a su empresa, ¿pueden contizarnos?<br/>B: Claro que sí. ¿Qué productos concretos quieren pedir?<br/>A: Planteamos pedir los productos del número 202, 203 y 303, 3000 piezas cada tipo. Que nos den el CIF Barcelona.<br/>B: Vale, esta tarde le mando la oferta.<br/>A: ¿Puede ofrecernos el FOB Hong Kong como referencia?<br>B: No hay problema.</font><font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><br/><br/><b>Diálogo 3</b><br/>A:¿Podría dar el precio del artículo némero tres?<br/>B: Por supuesto. ¿Quiere FOB o CIF?<br/>A:CIF Valencia.<br/B: Espere, ahora bien, aquí lo tiene.<br/>A: Gracias.¿Me ha dado la oferta real o esta cifra está sometida a la confirmación?<br/>B: La oferta real y es válida dentro de tres días.</font>";	
	}
	
	
