// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	   xianshi.innerHTML="<font color='#06C'style='font-family:Georgia, \"Times New Roman\"'>01.Hemos consultado precios de sus productos. Sírvanse hacernos la oferta antes del fin de este mes.<br/>02.	Dennos la oferta antes del final de octubre.<br/>03.	Si pueden bajar un poco más los precios, queremos firmar un contrato a largo plazo con ustedes.<br/>04.	Gracias por su consulta. ¿Podría decirnos de qué cantidad sería el pedido para que hagamos la oferta?<br/>05.	No puedo prometer la entrega en enero.<br/>06.	Es imposible reservar la fecha de navegación en diciembre.<br/>07.	Perdón, parece inevitable demorar el embarque.<br/>08.  Ahora tenemos las existencias que ha pedido su compañía, y aseguramos poder embarcarlas en el primer barco de noviembre.<br/>09.Vamos a hacer todo lo posible para cumplir este pedido y efectuar el embarque antes del día 15 de octubre.<br/> 10.	Creemos poder embarcar la mercancía antes del final del próximo mes.<br/>11.	¿Qué medios de transporte queréis?<br/> 12.	Si quieren pagar el transpote, pueden elegir el envío aéreo. <br/>13.	Espera tomar Tianjin como puerto de embarque, y Barcelona como puerto de destino, ¿verdad?<br/>14.	El puerto de Huangpu tiene capacidad muy grande de carga y descarga, y es un puerto muy moderno, no habrá problema como puerto de embarque.<br/>15. No estoy seguro de si podemos reservar el espacio necesario.<br/>16.	Supongo que no habrá problema para reservar espacio marítimo.<br/>17.	Aseguramos que les despacharemos las mercancías al lograr el espacio marítimo.<br/>18.	Una vez determinada la fecha de embarque, les avisaré.<br/>19.	Al terminar el embarque, les enviamos un E-mail/fax, o llamarles por teléfono  para avisarles.<br/>20.	Ya terminamos el embarque, y les he dado el aviso de embarque por fax.<br></font>";}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Hola, soy Li Dawei. Por favor, ¿en qué puedo servirle?<br/>B: Hola, habla Juan. Esta mañana recibimos los flores de vidrio mandados por ustedes. Después de abrir las cajas, encontramos algunos floreros rotos.<br/>A: No se preocupe. Hemos solicitado el seguro contra rotura para esta partida de mercancías. La empresa de seguro será responsable por esta reclamación.<br/> B: Haga el favor de comunicarse con la empresa de seguro ahora, para que nos tramite pronto un pago de las pérdidas.A: Bueno, voy a comunicarlo a la empresa de seguro en seguida.<br/>B: Muchas gracias.<br/><br/><b>Diálogo 2</b><br/>A: Cerramos el negocio con el precio CIF. Por eso ustedes deben arreglar el seguro por su cuenta, ¿verdad?<br/>B: Sí.<br/>A: Por favor ¿a qué empresa van a asegurar?<br/>B: Vamos a asegurar a la Empresa de Seguro del Pueblo de China.<br/>A: ¿Qué tipos de seguros tiene ella?<br/>B: Hay todo tipo de seguros. Podemos contraerlos según nuestra necesidad.<br/>A: Bueno, gracias.<br/><br/><br/><b>Diálogo 3</b><br/>A: Esta partida de mercancías está cerrada con el precio FOB. Por eso debemos arreglar el seguro por nuestra cuenta, ¿verdad?<br/>B: Sí.<br/>A: Según su experiencia, ¿qué tipos de seguros nos propone contraer?<br/>B: Propongo que cubran seguros contra avería particular, pillaje, robo y no-entrega.<br/>A: Bien, gracias.</font>";	
	}
	
	
