// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'>01.¿Qué peticiones tienen sobre el embalaje exterior e interior?<br/>02.La vez pasada me dijiste que querías el embarque más económico.<br/>03.Puedes darnos consejos sobre el embarque.<br/>04.¿Cuál es el embarque de mayor venta?<br/>05.El embalaje exterior require exactitud absoluta y claridad.<br/>06.En cuanto al embarque interior, debe tener atracción. Es favorable para la venta.<br/>07.Diseñamos meticulosamente los embalajes adecuados para cada partida de las mercancías.<br/>08.Pierden cuidado. Hemos perfeccionado mucho el embalaje.<br/>09.La especificación de nuestro contenedor cumoke absolutamente la norma de la  Organización Internacional de Estandarización.<br/>10.El precio de este artículo ya incluye el gasto del empaque.<br/>11.	Generalmente los gastos del empaque tienen que correr de la cuenta de la parte del comprador.<br/> 12.	¿Este empaque es conveniente para el largo transporte?<br/> 13.	Pedimos que el embalaje pueda soportar el largo viaje por el mar.<br/>14.Tenemos las peticiones especiales sobre el empaque.<br/>15.	Por elevadísimo que sea el precio, exigimos que embalen esta partida de mercancías en materiales especiales de envase.<br/> 16.	Haga el favor de marcar en la caja de embalaje el puerto de destino, las medidas, el número de serie, peso bruto y peso neto.<br/>17.	En cada carga de bultos deben marcar el puerto de destino, número, peso bruto y neto, tamaño y signo.<br/>18.	Para evitar los posibles daños sufridos en tránsito, pedimos que embalen en pequeñas cajas sólidos de madera.<br/>19.	La caja de madera no sólo tiene que ser muy conveniente para el tranporte de mar, sino también muy resistente para proteger las mercancías de la posible pérdida.<br/>20.	Pedimos que las cajas sean forradas impermeablemente, reforzadas con dos correas meteles.<br></font>";}

function xianshi2(){
       dialog.innerHTML="<font color='#06C' style='font-family:Georgia,\"Times New Roman\"'><b>Diálogo 1</b><br/>A: ¿Cómo se empaquetan estos instrumentos metales?<br/>B: Generamente de ipos. Aquí están las muestras.<br/>A: Son muy bonitos. ¿Cuál es el empaquete que se vende mejor?<br/>B: El empaque de membrana.<br/>A: ¿Es cierto?<br/>B: Sí, y también es el más nuevo de este producto en el mercado internacional. Es muy llamativo, y es muy bueno para la venta.<br/>A: Está bien, entonces ¿cómo está el empaque de la exportación?<br/>B: Dos docenas en una cajita, y cien cajitas en una caja de madera.<br/>A: ¿Cuánto pesa más o menos una caja de madera?<br/>B: Alrededor de 2500 kilos.<br/><br/><b>Diálogo 2</b><br/>A: Tenemos peticiones especiales sobre ell empaque.<br/>B: ¿Qué peticiones? Díganme los detalles.<br/>A: Cada camisa en un paquete del politeno.<br/>B: Estar dirá bien. De esta manera las camisas se pueden mostrar directamente en el escaparate para que los compradores la vean más de cerca.<br/>A: Tienes razón.<br/>B: ¿Cómo es el empaque exterior?<br/>A: Diez docenas en una caja de cartón. Las cajas forradas con plástico son impermeables. Las cajas deben reforzarse con cuerdas de plástico.<br/>B: Ok, nuestro empaque va a ser de su gusto, porque generalmente lo hacemos así.<br/><br/><br/><b>Diálogo 3</b><br/>A: Entonces ahora tenemos que discutir algo sobre el empaquete. ¿Qué material se usa para el empaque exterior?<br/>B: Con caja de tablas.<br/>A: ¿Es conveniente para el transporte del largo viaje?<br/>B: Sí.<br/>A: ¿Quién va a pagar el gasto del empaque?<br/>B: Según las costumbres internacionales, el gasto tiene que estar incluido.<br/>A: Está bien. Entiendo.</font>";	}
	
	
