// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	      xianshi.innerHTML="<font color='#06C'style='font-family:Georgia, \"Times New Roman\"'>01.	Sólo cubrimos franco de avería particular y seguros contra guerras.<br/>02.Esta partida de mercancías no es artículo frágil. No puede sufrir daños durante el transporte. Basta con franco de avería particular.<br/>03.	Si contratamos el franco de avería particular, una vez que se hunda, queme o encalle el barco, ¿ustedes nos pagarán todas las perdidas?<br/>04.	¿Me puede mandar las instrucciones para actuar en caso de avería, así como la forma de efectuar las indemnizaciones?<br/>05.  Quiero cambiar esta palabra por después de la entrega.<br/>06.	No tenemos sugerencia sobre las cláusulas del contrato, pero las condiciones de pago nos parecen exigentes.<br/>07.	La parte compradora debe pagar el 30% del total como entrada en el lapso de diez días después de firmar el contrato.<br/>08.  Al recibir el aviso del banco, la parte compradora transmitirá el pago en seguida.<br/>09.	Acerca de la reclamación solicitada por la parte compradora, le va a dar la respuesta lo más pronto posible la parte vendedora. <br/>10.	Creemos que es muy necesario añadir la cláusula de fuerza mayor.<br/>11.	Deseamos que no se opongan a que añadamos esta cláusul en el acuerdo.<br/>12.	Según el contrato, la reclamación se hace de acuerdo con el informe de inspección expedido por el Buró de Inspección de Mercancías de China.<br/>13.	Si surgen disputas entre la parte compradora y la parte vendedora, éstas deberán ser resueltas mediante amistosas consultas.<br/>14. Si no, las disputas deberán ser resueltas mediante el arbitraje o la sentencia judicial.<br/>15. El presente contrato está en dos ejemplares originales, y cada uno está escrito en los idiomas chino y español, siendo ambos textos de igual validez.<br/>16.	Sin apobación de ambas partes, no se puede introducir ninguna modificación en el contrato.<br/>17. Si no se entregan la mercancías de acuerdo con la fecha fijada, el contrato se  anulará.<br/>18.	Este contrato será válido durante un año, y entra en vigor desde el día de firmar.<br/>19.	Si cualquier parte piensa que no es necesario renovar este contrato, la parte de  sugerencia debe concertar negociar activamente con la otra parte en el mes  anterior al día de vecimiento del contrato.<br/>20.	Si una parte contraviene cualquier cláusula de este convenio, otra parte tiene  derecho a notificar a la parte contraria la terminación de este convenio por escrito.<br></font>";}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Hola, soy Li Dawei. Por favor, ¿en qué puedo servirle?<br/>B: Hola, habla Juan. Esta mañana recibimos los flores de vidrio mandados por ustedes. Después de abrir las cajas, encontramos algunos floreros rotos.<br/>A: No se preocupe. Hemos solicitado el seguro contra rotura para esta partida de mercancías. La empresa de seguro será responsable por esta reclamación.<br/> B: Haga el favor de comunicarse con la empresa de seguro ahora, para que nos tramite pronto un pago de las pérdidas.A: Bueno, voy a comunicarlo a la empresa de seguro en seguida.<br/>B: Muchas gracias.<br/><br/><b>Diálogo 2</b><br/>A: Cerramos el negocio con el precio CIF. Por eso ustedes deben arreglar el seguro por su cuenta, ¿verdad?<br/>B: Sí.<br/>A: Por favor ¿a qué empresa van a asegurar?<br/>B: Vamos a asegurar a la Empresa de Seguro del Pueblo de China.<br/>A: ¿Qué tipos de seguros tiene ella?<br/>B: Hay todo tipo de seguros. Podemos contraerlos según nuestra necesidad.<br/>A: Bueno, gracias.<br/><br/><br/><b>Diálogo 3</b><br/>A: Esta partida de mercancías está cerrada con el precio FOB. Por eso debemos arreglar el seguro por nuestra cuenta, ¿verdad?<br/>B: Sí.<br/>A: Según su experiencia, ¿qué tipos de seguros nos propone contraer?<br/>B: Propongo que cubran seguros contra avería particular, pillaje, robo y no-entrega.<br/>A: Bien, gracias.</font>";	
	}
	
	
