// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'>01.Deseo conocer los términos del seguro.<br/>02.Me gustaría que me aconsejase el tema de seguros.<br/>03.¿Nos puede dar una copia de la póliza? <br/>04.Queremos conocer las primas de seguros de transporte por barco o por avión.<br/>05.Quiero saber ¿cuánto tengo que pagar el riesgo contra rotura?06.Aseguren nuestros artículos del suplemento.<br/>07.Tenemos una partida de mercancías que se transportarán a España, y queremos conocer sus seguros contra riesgo marítimo.<br/>08.La prima de seguro marítimo corre por nuestra cuenta.<br/>09.Si concluimos el negocio con el percio FOB, ¿qué tipos de seguros nos recomienda cubrir?<br/>10.Esta partida de mercancías está cerrada con el precio CIF, y puede arreglar el seguro por su cuenta.<br/>11.Si cerramos el negocio con el precio CIF, ¿qué tipos de seguros corren por su cuenta?<br/>12.¿Qué tipos de seguros incluyen sus precios CIF?<br/>13.Los negocios de exportación concluidos a precio CIF, en general los aseguramos a la Empresa de Seguro del Pueblo de China.<br/>14.Tenga cuidado de elegir un envasado conveniente. Si no, la compañía de seguros rechazará la demanda de indemnización a causa de la inconveniencia del envasado.<br/>15.Aseguren nuertros envíos de Tianjin a Argentina del próximo mes.16.Aseguren los ordenadores que encargamos lo más pronto posible.<br/>17.Cúbranos seguros de 10% más que el valor nominal para esta mercancía.<br/>18.Contratamos seguros con avería particular de 100% más que el valor nominal para esta partida de mercancía. <br/>19.Aseguraremos esta partida de mercancías según el 120% del importe del precio CIF.<br/>20.Hemos tomado el seguro por ustedes según el importe total de la factura más un 12%.<br></font>";
}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Hola, soy Li Dawei. Por favor, ¿en qué puedo servirle?<br/>B: Hola, habla Juan. Esta mañana recibimos los flores de vidrio mandados por ustedes. Después de abrir las cajas, encontramos algunos floreros rotos.<br/>A: No se preocupe. Hemos solicitado el seguro contra rotura para esta partida de mercancías. La empresa de seguro será responsable por esta reclamación.<br/> B: Haga el favor de comunicarse con la empresa de seguro ahora, para que nos tramite pronto un pago de las pérdidas.A: Bueno, voy a comunicarlo a la empresa de seguro en seguida.<br/>B: Muchas gracias.<br/><br/><b>Diálogo 2</b><br/>A: Cerramos el negocio con el precio CIF. Por eso ustedes deben arreglar el seguro por su cuenta, ¿verdad?<br/>B: Sí.<br/>A: Por favor ¿a qué empresa van a asegurar?<br/>B: Vamos a asegurar a la Empresa de Seguro del Pueblo de China.<br/>A: ¿Qué tipos de seguros tiene ella?<br/>B: Hay todo tipo de seguros. Podemos contraerlos según nuestra necesidad.<br/>A: Bueno, gracias.<br/><br/><br/><b>Diálogo 3</b><br/>A: Esta partida de mercancías está cerrada con el precio FOB. Por eso debemos arreglar el seguro por nuestra cuenta, ¿verdad?<br/>B: Sí.<br/>A: Según su experiencia, ¿qué tipos de seguros nos propone contraer?<br/>B: Propongo que cubran seguros contra avería particular, pillaje, robo y no-entrega.<br/>A: Bien, gracias.</font>";	
	}
	
	
