// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C'style='font-family:Georgia, \"Times New Roman\"'>01.¿Podemos discutir las cláusulas del contrato hoy?<br/>02.¿Qué opinan ustedes de este proyecto?<br/>03.Estamos satisfechos con este proyecto.<br/>04.El contrato ya está listo.<br/>05.Si las cosas andan bien, vamos a firmar el contrato.<br/>06.¿Podría examinar todas las cláusulas del contrato antes de firmarlo?<br/>07.Es mejor que redactemos primero un proyecto contractual, y cuando nos veamos otra vez discutiremos los detalles.<br/>08.He aquí una muestra del contrato redactada por nosotros, en la cual están incluidas las condi ciones generales de venta.<br/>09.Pensamos que el contrato redactado por ustedes necesita alguna modificación.<br/>10.Antes de incluirlas finalmente en el contrato, pienso que vamos a discutir estas cláusulas esta tarde.<br/>11.Creemos que están bien todas las cláusulas.<br/>12.Ambas partes llegan a un consenso mediante la consulta.<br/>13.Estoy muy contento de firmar este contrato.<br/>14.La parte exportadora se encarga de la examinación de mercancías y la declaración aduanera.<br/>15.Nuestra parte gestiona un permiso de exportación, y su parte gestiona un permiso de importación.<br/>16.La parte china garantiza la calidad, la cantidad y la entrega de las mercancías a tiempo.<br/>17.La parte china se encarga de la consulta y el proyecto de obras.<br/>18.La parte española se ocupa de la compra del equipo y la construcción.<br/>19.La parte B debe abrir una carta de crédito dentro de 10 días.<br/>20.La parte A envía a un agente al puerto de exportación a verificar mercancías.<br/><br></font>";
}

function xianshi2(){
      dialog.innerHTML="<font color='#06C'style='font-family:Georgia,\"Times New Roman\"'><b>Diálogo 1</b><br/>A: ¿Podemos discutir las cláusulas del contrato hoy?<br/>B: Con mucho gusto. Venga directamente a mi oficina, ¿qué le parece?<br/>A: Bien, llegaré alas diez.<br/>B: ¡Ojalá que las cosas anden bien!<br/>A: ¿Cuándo firmamos el contrato?<br/>B: Pasado mañana por la mañana.<br/>A: Esta tarde podemos tenerlo redactado. Mañana enviaré una copia del contrato a su oficina para que usted lo revise.<br/>B: Después de recibir el contrato, tenemos que informar al director general. Una vez que lo autorice, podemos proceder a la firma.<br/>A: ¡Qué bien!<br/><br/><b>Diálogo 2</b><br/>A: Es posible que usted haya estudiado detenidamente el proyecto del contrato.<br/>B: Sí, debatimos el proyecto concienzudamente.<br/>A: ¿Qué opinan ustedes de este proyecto?<br/>B: Estamos de acuerdo con todas las cláusuras del contrato. Pero queremos añadir en la cáusura que la carta de crédito será válida hasta dos semanas después del embarque.<br/>A: Está bien. Se puede.<br/><br/><b>Diálogo 3</b><br/>A: El contrato ya está listo. Léalo, a ver si existe cierta inconveniencia.<br/B: ¿Podría decirme cuál es su última decisión en relación a la fecha de entrega?<br/>A: A primeros de mayo.B: Haga un favor de estipular en el contrato lo siguiente el embarque se efectuará antes del 5 de mayo.<br/>A: Vale, ¿algún otro problema?<br/>B: No.<br/>A: ¿Lo firmamos ahora mismo?<br/>B: Sí.<br/></font>";	}
	
	
