// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
// JavaScript Document
function xianshi1(){
	xianshi.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'>01.	¿Podemos discutir ahora los detalles de los términos de pago?<br/>02.	¿En qué moneda queréis pagar?<br/>03.	Además del dólar, deseamos que puedan aceptar pagos en otra moneda.<br/>04.	Me gustaría saber vuestra forma de pago.<br/>05.	¿Aceptáis el pago a plazos?<br/>06.	¿Aceptáis documentos contra el pago<br/>07.	P roponemos que se paguen el 20% como entrada y el resto se pague a plazos mensualmente.<br/>08.	¿Aceptan ustedes documentos contra el pago o documentos contra la aceptación?<br/>09.	Sólo en el caso muy especial, aceptamos documentos contra la aceptación.<br/>10.	Espero que nos haga una excepción, que acepten documentos contra el pago o documentos contra la aceptación.<br/>11.	Para llegar a un acuerdo, aceptamos documentos contra el pago.<br/>12.	Pagar mercancías con letras de crédito es nuestra forma de pago más habitual.<br/>13.	Abriremos una letra de crédito a su favor y haremos la liquidación en dólares.<br/>14.	Como normas básicas, pedimos que se pague con carta de crédito irrevocable y confirmada.<br/>15.	¿Cuándo crees que abriremos la carta de crédito?<br/>16.	Abra la carta de crédito cuanto antes, para cargar las mercancías a bordo.<br/>17.	Si podéis entregar la mercancía con anticipación de un mes, puedo pagaros con la carta de crédito.<br/>18.	Al regresar a su país, abra una carta de crédito a nuestro favor, ¿de acuerdo?<br/>19.	Abra una carta de crédito a nuestro favor, la suma de dinero es 500,000 euros, y será válida hasta el día 21 de marzo.<br/>20.	¿Es de cuántos días esta carta de crédito?<br></font>";}

function xianshi2(){
dialog.innerHTML="<font color='#06C' style='font-family:Georgia, \"Times New Roman\"'><b>Diálogo 1</b><br/>A: Sr. Li, me gustaría saber su forma del pago.<br/>B: Ahora no podemos pagarle en efectivo, porque también nos falta.<br/>A: Está bien. ¿Puede pagar el 30% de la cuenta cuando hace el pedido y pagar el resto con letra a plazo dentro de 3 meses? <br/>B: OK.<br/><br/><b>Diálogo 2</b><br/>A: ¿Puede permitirnos que le paguemos por varias veces?<br/>B: Creo que no.<br/> A: ¿Entonces puede prolongar el plazo del pago?<br/>B: Generalmente se pagará dentro de 30 días después de que las mercancías lleguen al puerto de descarga.<br/>A: ¿Estos días hay muchos problemas en nuestra circulación del fondo, puede retrasarlo hasta 60 días?<br/>B: En consideración a su condición de ser el primer cliente mexicano, estamos de acuerdo.<br/><br/><br/><b>Diálogo 3</b><br/>A: ¿Aceptan D/P?<br/>B: Creo que esta vez no, porque éste es el primer negocio entre nosotros. Insisten en que se paque con L/C. <br/>A: Está bien, no tenemos otro remedio. Entonces ¿cuándo podemos abrir L/C si queremes que nos envíen la mercancía antes del final de octubre?<br/>B: Generalmente nuestro banco pide que se abra la carta de crédito un mes antes de efectuar el envío. Por eso, tiene que abrirla antes del final de septiembre.<br/>A: Sí, voy a hacerlo a tiempo.<br/>B: Si es así, la mercancía llegará antes de la Navidad. Entonces pueden ganar bien.<br/>A: Eso es lo que esperamos.</font>";	}
	
	
